### ISSUE TITLE
error using mmap version. would you know why?

### ISSUE THREAD

**Issue by kolinfluence** [viant/scache#6]
after running for a very prolonged time for 100MB size mmap cache, this happens.
```
unexpected fault address 0x7f3935164000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f3935164000 pc=0x63d635]

goroutine 1 [running]:
runtime.throw({0xa7cfad?, 0xa7f77d?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0000c9018 sp=0xc0000c8fe8 pc=0x55ca7d
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:838 +0x125 fp=0xc0000c9078 sp=0xc0000c9018 pc=0x572c65
github.com/viant/scache.(*segment).set(0xc00011e100?, {0xc006321550?, 0xc052c3e180?}, {0xc006321500?, 0x7f3918fc0698?, 0x7f397135a5b8?})
        /root/go/pkg/mod/github.com/viant/scache@v0.5.0/segment.go:103 +0x95 fp=0xc0000c90c8 sp=0xc0000c9078 pc=0x63d635
github.com/viant/scache.(*Cache).Set(0xc000105040, {0xc006321550, 0x9}, {0xc006321500, 0xb, 0x10})
        /root/go/pkg/mod/github.com/viant/scache@v0.5.0/cache.go:53 +0x9b fp=0xc0000c9158 sp=0xc0000c90c8 pc=0x63c39b

```

**Comment by kolinfluence** [comment]
just realised u need to set max entries and entry sizes to prevent from OOM.
